#!/usr/bin/env python3
"""Create a .gitignore skeleton and optionally initialize a git repository."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_IGNORES = [
    ".cursor/",
    ".build/",
    ".debug/",
    ".DS_Store",
]

HEADER = "# Generated by newgit\n"


def config_path() -> Path | None:
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return Path(xdg) / "newgit" / "ignore"
    home = Path.home()
    if home:
        return home / ".config" / "newgit" / "ignore"
    return None


def load_config_file(path: Path) -> list[str] | None:
    if not path.is_file():
        return None
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        entries.append(stripped)
    return entries


def resolve_entries(cli_ignore: list[str] | None, use_defaults: bool) -> list[str]:
    if cli_ignore:
        return cli_ignore
    if use_defaults:
        return DEFAULT_IGNORES
    cfg = config_path()
    if cfg:
        entries = load_config_file(cfg)
        if entries is not None:
            return entries
    return DEFAULT_IGNORES


def write_gitignore(path: Path, entries: list[str]) -> None:
    text = HEADER + "\n".join(entries) + "\n"
    path.write_text(text, encoding="utf-8")


def merge_gitignore(existing: Path, entries: list[str]) -> list[str]:
    current = set(existing.read_text(encoding="utf-8").splitlines())
    merged = []
    for entry in entries:
        if entry not in current:
            merged.append(entry)
    return merged


def prompt_existing_gitignore(path: Path) -> str:
    while True:
        choice = input(f"{path} already exists. [o]verwrite / [a]ppend / [q]uit: ").strip().lower()
        if choice in {"o", "overwrite"}:
            return "overwrite"
        if choice in {"a", "append"}:
            return "append"
        if choice in {"q", "quit", ""}:
            return "quit"
        print("Invalid choice.")


def prompt_git_init() -> bool:
    while True:
        choice = input("Run git init? [y/N]: ").strip().lower()
        if choice in {"y", "yes"}:
            return True
        if choice in {"n", "no", ""}:
            return False
        print("Invalid choice.")


def run_git_init(target: Path) -> None:
    git = shutil.which("git")
    if not git:
        print("git not found in PATH.", file=sys.stderr)
        return
    subprocess.run([git, "init"], cwd=target, check=False)


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="newgit",
        description="Create a .gitignore skeleton and optionally run git init.",
    )
    parser.add_argument("path", nargs="?", default=".", help="Target directory (default: current directory)")
    parser.add_argument("-i", "--ignore", nargs="+", help="Override ignore patterns for this run")
    parser.add_argument("--defaults", action="store_true", help="Use built-in defaults instead of config file")
    git_group = parser.add_mutually_exclusive_group()
    git_group.add_argument("--git-init", action="store_true", dest="git_init", help="Run git init without prompting")
    git_group.add_argument("--no-git-init", action="store_true", dest="no_git_init", help="Do not run git init")
    args = parser.parse_args()

    target = Path(args.path).expanduser().resolve()
    if not target.is_dir():
        print(f"Error: {target} is not a directory.", file=sys.stderr)
        return 1

    entries = resolve_entries(args.ignore, args.defaults)
    if not entries:
        print("No ignore patterns to write.", file=sys.stderr)
        return 1

    gitignore = target / ".gitignore"
    if gitignore.exists():
        choice = prompt_existing_gitignore(gitignore)
        if choice == "quit":
            return 0
        if choice == "append":
            new_entries = merge_gitignore(gitignore, entries)
            if not new_entries:
                print("All patterns already present; nothing to append.")
                return 0
            existing_text = gitignore.read_text(encoding="utf-8")
            if not existing_text.endswith("\n"):
                existing_text += "\n"
            gitignore.write_text(existing_text + "\n".join(new_entries) + "\n", encoding="utf-8")
            print(f"Appended {len(new_entries)} pattern(s) to {gitignore}")
        else:
            write_gitignore(gitignore, entries)
            print(f"Overwrote {gitignore}")
    else:
        write_gitignore(gitignore, entries)
        print(f"Created {gitignore}")

    git_dir = target / ".git"
    if git_dir.exists():
        print(f"{target} is already a git repository.")
        return 0

    if args.git_init:
        run_git_init(target)
    elif args.no_git_init:
        pass
    else:
        if prompt_git_init():
            run_git_init(target)

    return 0


if __name__ == "__main__":
    sys.exit(main())
