#!/usr/bin/env python3
"""Create a .gitignore skeleton and optionally initialize a git repository."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_IGNORES = [
    "# Editor / IDE",
    ".cursor/",
    "# Build / debug artifacts",
    ".build/",
    ".debug/",
    "# macOS",
    ".DS_Store",
    "# Secrets and credentials",
    ".env",
    ".env.*",
    "!.env.example",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "*.keystore",
    "*.jks",
    "id_rsa",
    "id_rsa.pub",
    "id_dsa",
    "id_dsa.pub",
    "id_ecdsa",
    "id_ecdsa.pub",
    "id_ed25519",
    "id_ed25519.pub",
    "secrets/",
    "credentials/",
    "private/",
]

HEADER = "# Generated by newgit\n"

# Pre-commit hook content. Kept as a raw string so regex backslashes are preserved.
PRE_COMMIT_HOOK = r'''#!/usr/bin/env python3
"""Pre-commit hook: block commits that contain secrets or private keys."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

# Patterns that indicate a secret or private key.
BLOCKED_PATTERNS = [
    re.compile(r"-----BEGIN (RSA |OPENSSH |EC |DSA |ENCRYPTED |)?PRIVATE KEY-----"),
    re.compile(r"AKIA[0-9A-Z]{16}"),  # AWS Access Key ID
    re.compile(r"\b[aA][pP][iI][_-]?[kK][eE][yY]\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{16,}['\"]?"),
    re.compile(r"\b[sS][eE][cC][rR][eE][tT][_-]?[kK][eE][yY]\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{16,}['\"]?"),
    re.compile(r"\b[pP][rR][iI][vV][aA][tT][eE][_-]?[kK][eE][yY]\s*[:=]\s*['\"]?[A-Za-z0-9_+/=\-]{16,}['\"]?"),
    re.compile(r"\b[aA][uU][tT][hH][_-]?[tT][oO][kK][eE][nN]\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{16,}['\"]?"),
    re.compile(r"\b[aA][cC][cC][eE][sS][sS][_-]?[tT][oO][kK][eE][nN]\s*[:=]\s*['\"]?[A-Za-z0-9_\-]{16,}['\"]?"),
]

SENSITIVE_FILENAMES = {
    ".env", ".env.local", ".env.production", ".env.development", ".envrc",
    "id_rsa", "id_dsa", "id_ecdsa", "id_ed25519",
}

SENSITIVE_EXTENSIONS = (".pem", ".key", ".p12", ".pfx", ".keystore", ".jks")


def get_staged_files() -> list[str]:
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
        capture_output=True, text=True, check=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def read_staged_file(path: str) -> str:
    result = subprocess.run(
        ["git", "show", f":{path}"],
        capture_output=True, text=True, check=True,
    )
    return result.stdout


def filename_is_sensitive(path: str) -> bool:
    name = Path(path).name.lower()
    if name in SENSITIVE_FILENAMES:
        return True
    return name.endswith(SENSITIVE_EXTENSIONS)


def content_has_secret(text: str) -> list[str]:
    matches = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        for pattern in BLOCKED_PATTERNS:
            if pattern.search(line):
                matches.append(f"line {line_no}: {line.strip()}")
                break
    return matches


def main() -> int:
    staged = get_staged_files()
    if not staged:
        return 0

    blocked = []
    for path in staged:
        if filename_is_sensitive(path):
            blocked.append((path, "sensitive filename"))
            continue
        text = read_staged_file(path)
        matches = content_has_secret(text)
        if matches:
            blocked.append((path, "\n".join(matches)))

    if blocked:
        print("ERROR: commit blocked — possible secrets or private keys detected:", file=sys.stderr)
        for path, reason in blocked:
            print(f"\n{path}:", file=sys.stderr)
            print(reason, file=sys.stderr)
        print("\nRemove or redact these values before committing.", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def config_path() -> Path | None:
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return Path(xdg) / "newgit" / "ignore"
    home = Path.home()
    if home:
        return home / ".config" / "newgit" / "ignore"
    return None


def load_config_file(path: Path) -> list[str] | None:
    if not path.is_file():
        return None
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        entries.append(stripped)
    return entries


def resolve_entries(cli_ignore: list[str] | None, use_defaults: bool) -> list[str]:
    if cli_ignore:
        return cli_ignore
    if use_defaults:
        return DEFAULT_IGNORES
    cfg = config_path()
    if cfg:
        entries = load_config_file(cfg)
        if entries is not None:
            return entries
    return DEFAULT_IGNORES


def write_gitignore(path: Path, entries: list[str]) -> None:
    text = HEADER + "\n".join(entries) + "\n"
    path.write_text(text, encoding="utf-8")


def merge_gitignore(existing: Path, entries: list[str]) -> list[str]:
    current = set(existing.read_text(encoding="utf-8").splitlines())
    merged = []
    for entry in entries:
        if entry not in current:
            merged.append(entry)
    return merged


def prompt_existing_gitignore(path: Path) -> str:
    while True:
        choice = input(f"{path} already exists. [o]verwrite / [a]ppend / [q]uit: ").strip().lower()
        if choice in {"o", "overwrite"}:
            return "overwrite"
        if choice in {"a", "append"}:
            return "append"
        if choice in {"q", "quit", ""}:
            return "quit"
        print("Invalid choice.")


def prompt_git_init() -> bool:
    while True:
        choice = input("Run git init? [y/N]: ").strip().lower()
        if choice in {"y", "yes"}:
            return True
        if choice in {"n", "no", ""}:
            return False
        print("Invalid choice.")


def prompt_install_hook() -> bool:
    while True:
        choice = input("Install secret-scanning pre-commit hook? [Y/n]: ").strip().lower()
        if choice in {"y", "yes", ""}:
            return True
        if choice in {"n", "no"}:
            return False
        print("Invalid choice.")


def run_git_init(target: Path) -> bool:
    git = shutil.which("git")
    if not git:
        print("git not found in PATH.", file=sys.stderr)
        return False
    result = subprocess.run([git, "init"], cwd=target, check=False)
    return result.returncode == 0


def install_precommit_hook(target: Path) -> bool:
    git = shutil.which("git")
    if not git:
        print("git not found in PATH; cannot install pre-commit hook.", file=sys.stderr)
        return False
    hook_dir = target / ".git" / "hooks"
    if not hook_dir.is_dir():
        print(f"{target} does not appear to be a git repository; skipping hook install.", file=sys.stderr)
        return False
    hook = hook_dir / "pre-commit"
    if hook.exists():
        print(f"A pre-commit hook already exists at {hook}; leaving it untouched.")
        return False
    hook.write_text(PRE_COMMIT_HOOK, encoding="utf-8")
    hook.chmod(0o755)
    print(f"Installed secret-scanning pre-commit hook at {hook}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="newgit",
        description="Create a .gitignore skeleton and optionally run git init.",
    )
    parser.add_argument("path", nargs="?", default=".", help="Target directory (default: current directory)")
    parser.add_argument("-i", "--ignore", nargs="+", help="Override ignore patterns for this run")
    parser.add_argument("--defaults", action="store_true", help="Use built-in defaults instead of config file")
    parser.add_argument("--no-precommit", action="store_true", help="Do not install the secret-scanning pre-commit hook")
    git_group = parser.add_mutually_exclusive_group()
    git_group.add_argument("--git-init", action="store_true", dest="git_init", help="Run git init without prompting")
    git_group.add_argument("--no-git-init", action="store_true", dest="no_git_init", help="Do not run git init")
    args = parser.parse_args()

    target = Path(args.path).expanduser().resolve()
    if not target.is_dir():
        print(f"Error: {target} is not a directory.", file=sys.stderr)
        return 1

    entries = resolve_entries(args.ignore, args.defaults)
    if not entries:
        print("No ignore patterns to write.", file=sys.stderr)
        return 1

    gitignore = target / ".gitignore"
    if gitignore.exists():
        choice = prompt_existing_gitignore(gitignore)
        if choice == "quit":
            return 0
        if choice == "append":
            new_entries = merge_gitignore(gitignore, entries)
            if not new_entries:
                print("All patterns already present; nothing to append.")
            else:
                existing_text = gitignore.read_text(encoding="utf-8")
                if not existing_text.endswith("\n"):
                    existing_text += "\n"
                gitignore.write_text(existing_text + "\n".join(new_entries) + "\n", encoding="utf-8")
                print(f"Appended {len(new_entries)} pattern(s) to {gitignore}")
        else:
            write_gitignore(gitignore, entries)
            print(f"Overwrote {gitignore}")
    else:
        write_gitignore(gitignore, entries)
        print(f"Created {gitignore}")

    git_dir = target / ".git"
    if git_dir.exists():
        print(f"{target} is already a git repository.")
        if not args.no_precommit and prompt_install_hook():
            install_precommit_hook(target)
        return 0

    if args.git_init:
        if run_git_init(target) and not args.no_precommit:
            install_precommit_hook(target)
    elif args.no_git_init:
        pass
    else:
        if prompt_git_init():
            if run_git_init(target) and not args.no_precommit:
                install_precommit_hook(target)

    return 0


if __name__ == "__main__":
    sys.exit(main())
